"""add sms_subscription to users

Revision ID: 72594d940d82
Revises: eeb2a0eda398
Create Date: 2026-03-07 11:05:06.183987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72594d940d82'
down_revision: Union[str, None] = 'eeb2a0eda398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sms_subscription', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sms_subscription')
    # ### end Alembic commands ###
