"""add search_trends table

Revision ID: 1e704150d2d8
Revises: a12767ffd14a
Create Date: 2026-03-26 16:12:07.598147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e704150d2d8'
down_revision: Union[str, None] = 'a12767ffd14a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_trends_id'), 'search_trends', ['id'], unique=False)
    op.create_index(op.f('ix_search_trends_term'), 'search_trends', ['term'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_trends_term'), table_name='search_trends')
    op.drop_index(op.f('ix_search_trends_id'), table_name='search_trends')
    op.drop_table('search_trends')
    # ### end Alembic commands ###
