"""add delivery house number

Revision ID: 6a7dc2b49731
Revises: edec93d76b8e
Create Date: 2026-02-25 16:51:04.909381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7dc2b49731'
down_revision: Union[str, None] = 'edec93d76b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_house_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_house_number')
    # ### end Alembic commands ###
