"""add stock columns to shop_products 

Revision ID: 7776fad139ac
Revises: 1e704150d2d8
Create Date: 2026-03-27 08:28:19.634891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7776fad139ac'
down_revision: Union[str, None] = '1e704150d2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add the columns but allow NULL temporarily
    op.add_column('shop_products', sa.Column('stock', sa.Integer(), nullable=True))
    op.add_column('shop_products', sa.Column('low_stock_threshold', sa.Integer(), nullable=True))
    
    # 2. Update existing rows with default values
    op.execute("UPDATE shop_products SET stock = 0")
    op.execute("UPDATE shop_products SET low_stock_threshold = 5")
    
    # 3. Alter the columns to set NOT NULL constraints
    op.alter_column('shop_products', 'stock', nullable=False)
    op.alter_column('shop_products', 'low_stock_threshold', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_products', 'low_stock_threshold')
    op.drop_column('shop_products', 'stock')
    # ### end Alembic commands ###
