"""add_lat_long_to_user_addresses

Revision ID: 68ba00da1537
Revises: 6a7dc2b49731
Create Date: 2026-03-04 14:31:35.553707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ba00da1537'
down_revision: Union[str, None] = '6a7dc2b49731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_addresses', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('user_addresses', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_addresses', 'longitude')
    op.drop_column('user_addresses', 'latitude')
    # ### end Alembic commands ###
