"""Add soft delete columns

Revision ID: 9c5e0d485463
Revises: 72594d940d82
Create Date: 2026-03-09 11:46:08.043652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5e0d485463'
down_revision: Union[str, None] = '72594d940d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('coupons', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('outlets', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_column('products', 'is_deleted')
    op.drop_column('outlets', 'is_deleted')
    op.drop_column('coupons', 'is_deleted')
    op.drop_column('categories', 'is_deleted')
    # ### end Alembic commands ###
