"""add category seo meta

Revision ID: e9184d01df37
Revises: 7e77145f6115
Create Date: 2026-03-20 16:00:23.693215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9184d01df37'
down_revision: Union[str, None] = '7e77145f6115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('meta_title', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('meta_description', sa.Text(), nullable=True))
    op.drop_constraint('coupon_usage_coupon_id_fkey', 'coupon_usage', type_='foreignkey')
    op.create_foreign_key(None, 'coupon_usage', 'coupons', ['coupon_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupon_usage', type_='foreignkey')
    op.create_foreign_key('coupon_usage_coupon_id_fkey', 'coupon_usage', 'coupons', ['coupon_id'], ['id'])
    op.drop_column('categories', 'meta_description')
    op.drop_column('categories', 'meta_title')
    # ### end Alembic commands ###
