"""add_razorpay_fields

Revision ID: 61a6d2979c32
Revises: 68ba00da1537
Create Date: 2026-03-05 11:35:44.204468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a6d2979c32'
down_revision: Union[str, None] = '68ba00da1537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('razorpay_payment_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('razorpay_signature', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'razorpay_signature')
    op.drop_column('orders', 'razorpay_payment_id')
    op.drop_column('orders', 'razorpay_order_id')
    # ### end Alembic commands ###
