"""add images column to products

Revision ID: 7e77145f6115
Revises: 9c5e0d485463
Create Date: 2026-03-11 05:49:57.103481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e77145f6115'
down_revision: Union[str, None] = '9c5e0d485463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'images')
    # ### end Alembic commands ###
